name: Call Delete StackSet Workflow
on:
  workflow_dispatch:
    inputs:
      stack-set-name:
        description: 'Stack-set name to delete'
        required: true
      aws-region:
        description: 'AWS region where the stack-set is deployed'
        required: true
      account-ids:
        description: 'Comma-separated list of account IDs to delete the StackSet instances from'
        required: true

jobs:
  call-delete-stackset:
    runs-on: ubuntu-latest
    steps:
      - name: Call Delete StackSet Workflow
        uses: ./.github/workflows/stackset_workflow.yml
        with:
          stack-set-name: ${{ github.event.inputs.stack-set-name }}
          aws-region: ${{ github.event.inputs.aws-region }}
          account-ids: ${{ github.event.inputs.account-ids }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
