---
name: Cloudformation stack-set & stack-set-instances
on:
  workflow_call:
    inputs:
      aws-region:
        description: 'AWS region (in this region stackset enabled)'
        required: false
        default: 'us-east-2'
        type: string
      stackset-instance-region:
        description: 'Stackset-instance regions where you need CloudFormation stacks'
        required: false
        default: 'us-east-2'
        type: string
      stack-set-name:
        description: 'Stack-set name defined here'
        required: true
        type: string
      delete-stackset:
        description: 'Set to true if you want to delete the StackSet and instances'
        required: false
        default: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_SESSION_TOKEN:
        required: false
      AWS_ROLE_TO_ASSUME:
        required: false
      account-ids:
        description: 'Account IDs for self-managed permission'
        required: false

jobs:
  delete-stack-instances:
    if: inputs.delete-stackset == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}

      - name: Delete Stack Instances
        run: |
          echo "Deleting stack instances for ${{ inputs.stack-set-name }}..."
          aws cloudformation delete-stack-instances \
            --stack-set-name "${{ inputs.stack-set-name }}" \
            --regions ${{ inputs.stackset-instance-region }} \
            --accounts ${ACCOUNTS:=${{ secrets.account-ids }}} \
            --no-retain \
            --operation-preferences MaxConcurrentCount=1

  delete-stackset:
    if: inputs.delete-stackset == 'true'
    needs: delete-stack-instances
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}

      - name: Delete StackSet
        run: |
          echo "Deleting stack set ${{ inputs.stack-set-name }}..."
          aws cloudformation delete-stack-set \
            --stack-set-name "${{ inputs.stack-set-name }}"

